import './globals.css'
import NavBar from '@/app/components/NavBar'
import AISidePanel from '@/app/components/AISidePanel'
import { SelectedToAddProvider } from '@/app/components/SelectedToAddContext'
import AIContextProvider from '@/app/components/AIContextProvider'

export const metadata = {
  title: 'switch',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SelectedToAddProvider>
          <AIContextProvider>
            <NavBar />
            <main className="relative">
              {children}
            </main>
            <AISidePanel />
          </AIContextProvider>
        </SelectedToAddProvider>
      </body>
    </html>
  )
}
